replicaCount: 1

app:
  namespace: default
  name: sample-consumer
  port: 8888
  env: prod
  image_pull_policy: IfNotPresent
  type: consumer
  mem_limit: 0
  mem_required: 0
  cpu_limit: 100
  cpu_required: 0
  storage_limit: 0
  storage_required: 0
  node_selectors:
    business-type: fulfillment

config:
  remote-address: 10.0.160.37:8500
  remote-keys: /database/mysql/conf.toml,/database/entity/conf.toml
  sd-address:  10.0.160.37:8500
  tracing-address: no-addr


image:
  name: nexus.lionnix.net/consumer/sample-consumer
  tag: latest

# only set for internet exposed api like api-gateway or tracking.
# for other app, leave it as is
service:
  type:
  nodePort: 0