basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample Gin API with swaggo documentation.
  title: API
  version: "1.0"
paths:
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
